name: pull_request

on:
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run workflow on'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # prevent shallow clone

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build
